sources:
  - name: lordsbridgegoerli
    handler:
      graphql:
        endpoint: "${BRIDGE_SUBGRAPH_URL}"
  - name: apibara
    handler:
      graphql:
        endpoint: "${APIBARA_URL}"
documents:
  - "./queries/**/*.graphql"
