sources:
  - name: lordsbridgegoerli
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/redbeardeth/starknet-bridge-goerli
  - name: apibara
    handler:
      graphql:
        endpoint: https://p01--graphql-1--xkl8lp5qw8r7.code.run/graphql
documents:
  - "./queries/**/*.graphql"
