sources:
  - name: lordsbridge
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/{context.subgraphName:redbeardeth/starknet-bridge-mainnet}
  - name: apibara
    handler:
      graphql:
        endpoint: http://localhost:8080/{context.apibaraHandle:goerli-graphql}
  - name: l1Realms
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/{context.realmsSubgraph:bibliothecaforadventurers/realms}
documents:
  - "./queries/**/*.graphql"
