version: "3"

services:
  
  mongo-goerli:
    image: mongo:latest
    container_name: mongo-goerli
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: apibara
      MONGO_INITDB_ROOT_PASSWORD: apibara
    ports:
    - 27017:27017
    volumes:
    - ./mongo-data/goerli:/data/db
    networks:
    - goerli_network

  mongo-mainnet:
    image: mongo:latest
    container_name: mongo-mainnet
    restart: always
    command: mongod --port 27018
    environment:
      MONGO_INITDB_ROOT_USERNAME: apibara
      MONGO_INITDB_ROOT_PASSWORD: apibara
    ports:
    - 27018:27018
    volumes:
    - ./mongo-data/mainnet:/data/db
    networks:
    - mainnet_network


volumes:
  mongo-data:

networks:
  mainnet_network:
  goerli_network:
